# #############################################################################
# Do not delete the `UNIQUE_ID` line below, I use it to backup original files
# so they're not lost when my symlinks are applied
# UNIQUE_ID=do_not_delete_this_line
# #############################################################################

# import = ["~/github/dotfiles-public/alacritty/themes/dracula/dracula.toml"]
import = ["~/github/dotfiles-public/alacritty/themes/catppuccin/catppuccin-mocha.toml"]
# import = ["~/github/dotfiles-public/alacritty/themes/catppuccin/catppuccin-macchiato.toml"]
# import = ["~/github/dotfiles-public/alacritty/themes/catppuccin/catppuccin-frappe.toml"]
# import = ["~/github/dotfiles-public/alacritty/themes/catppuccin/catppuccin-latte.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"
# TERM: screen-256color

[font]
size = 14

[font.normal]
# family = "MesloLGSDZ Nerd Font"
# family = "MesloLGMDZ Nerd Font"
# family = "MesloLGS Nerd Font"
# family = "MesloLGLDZ Nerd Font"
# family = "MesloLGL Nerd Font"
family = "MesloLGM Nerd Font" # top pick
# family = "MesloLGSDZ Nerd Font Mono"
# family = "MesloLGLDZ Nerd Font Mono"
# family = "MesloLGLDZ Nerd Font Propo"
# family = "MesloLGMDZ Nerd Font Propo"
# family = "MesloLGM Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
# family = "MesloLGM Nerd Font Propo"
# family = "MesloLGL Nerd Font Propo"
# family = "MesloLGSDZ Nerd Font Propo"
# family = "MesloLGS Nerd Font Propo"
# family = "MesloLGL Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[shell]
# The 2 commands after login are needed to automatically attach to an existing tmux session
# If no session exists, a new one is created
args = ["--login", "-c", "/opt/homebrew/bin/tmux attach || //opt/homebrew/bin/tmux"]
program = "/bin/zsh"

[window]
opacity = 1
# Make `Option` key behave as `Alt` (macOS only):
#   - OnlyLeft
#   - OnlyRight
#   - Both
#   - None (default)
# I left this option commented out, it worked when I tried to use the
# option key as the Meta key in tmux to switch layouts (ctrl+b option+1)
# But it messed up my hyper key, so if I enable it, I cant do hyper+b
# which is what I use for tmux commands instead of ctrl+b
# option_as_alt = "Both"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 200
lines = 55

[window.padding]
x = 10
y = 10

[window.position]
x = 2750
y = 1100

# I don't need to enable this, as I normally select in visual mode and yank
# But apparently it allows you to copy to clipboard by just selecting the text
[selection]
save_to_clipboard = true

