import = ["/Users/krishna/github/dotfiles-public/alacritty/themes/dracula.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "MesloLGM Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["--login", "-c", "/opt/homebrew/bin/tmux attach || //opt/homebrew/bin/tmux"]
program = "/bin/zsh"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 200
lines = 55

[window.padding]
x = 10
y = 10

[window.position]
x = 2750
y = 1100
